In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
data = pd.read_csv("supplement.csv")
data.head()

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0  T1000001         1         S1            L3          R1  2018-01-01   
1  T1000002       253         S4            L2          R1  2018-01-01   
2  T1000003       252         S3            L2          R1  2018-01-01   
3  T1000004       251         S2            L3          R1  2018-01-01   
4  T1000005       250         S2            L3          R4  2018-01-01   

   Holiday Discount  #Order     Sales  
0        1      Yes       9   7011.84  
1        1      Yes      60  51789.12  
2        1      Yes      42  36868.20  
3        1      Yes      23  19715.16  
4        1      Yes      62  45614.52

In [3]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127021 entries, 0 to 127020
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             127021 non-null  object 
 1   Store_id       127021 non-null  int64  
 2   Store_Type     127021 non-null  object 
 3   Location_Type  127021 non-null  object 
 4   Region_Code    127021 non-null  object 
 5   Date           127021 non-null  object 
 6   Holiday        127021 non-null  int64  
 7   Discount       127021 non-null  object 
 8   #Order         127021 non-null  int64  
 9   Sales          127021 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 9.7+ MB


In [5]:
data.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [6]:
data.describe()

Store_id        Holiday         #Order          Sales
count  127021.000000  127021.000000  127021.000000  127021.000000
mean      183.001142       0.129309      67.734422   42212.875139
std       105.366814       0.335543      29.731920   17691.194838
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30336.000000
50%       183.000000       0.000000      62.000000   39378.000000
75%       274.000000       0.000000      81.000000   51201.000000
max       365.000000       1.000000     333.000000  219984.000000

In [7]:
import plotly.express as px

In [8]:
pie = data["Store_Type"].value_counts()
store = pie.index
order = pie.values

fig = px.pie(data, values = order, names = store)
fig.show()

In [10]:
pie = data["Location_Type"].value_counts()
Location = pie.index
order = pie.values

fig = px.pie(data, values = order, names = Location)
fig.show()

In [11]:
pie = data["Discount"].value_counts()
discount = pie.index
order = pie.values

fig = px.pie(data, values = order, names = discount)
fig.show()

In [12]:
pie = data["Holiday"].value_counts()
Holiday = pie.index
order = pie.values

fig = px.pie(data, values = order, names = Holiday)
fig.show()

In [13]:
data["Discount"] = data["Discount"].map({"Yes":1, "No":0}) 

In [14]:
data

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
127016  T1127017       147         S4            L2          R4  2018-12-14   
127017  T1127018        24         S1            L1          R2  2018-12-14   
127018  T1127019       107         S1            L3          R3  2018-12-14   
127019  T1127020       251         S2            L3          R1  2018-12-14   
127020  T1127021       328         S1            L3          R1  2018-12-15   

        Holiday  Discount  #Order     Sales  
0             1         1       9   7011.84  
1             1         1      60  51789.12  
2             1         1      42  36868.20  
3             1         1      23  19715.16  
4             1         1      62  45614.52  
...         ...       ...     ...       ...  
127016        0         1     132  76188.00  
127017        0         0      59  33291.00  
127018        0         0      59  32550.00  
127019        0         1      52  33957.00  
127020        0         0      55  32715.00  

[127021 rows x 10 columns]

In [15]:
data["Store_Type"] = data["Store_Type"].map({"S1":1,"S2":2,"S3":3, "S4":4}) 

In [16]:
data["Location_Type"] = data["Location_Type"].map({"L1":1,"L2":2,"L3":3,"L4":4,"L5":5}) 

In [17]:
X = np.array(data[{"Store_Type","Location_Type","Discount","Discount"}])
y = np.array(data["#Order"])

<ipython-input-17-cc9f5162aa1d>:1: FutureWarning:

Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.



In [18]:
X

array([[1, 1, 3],
       [1, 4, 2],
       [1, 3, 2],
       ...,
       [0, 1, 3],
       [1, 2, 3],
       [0, 1, 3]])

In [19]:
y

array([ 9, 60, 42, ..., 59, 52, 55])

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [22]:
len(X_train)

85104

In [23]:
import lightgbm as ltb
model = ltb.LGBMRegressor()

In [24]:
model.fit(X_train,y_train)

LGBMRegressor()

In [25]:
y_pred = model.predict(X_test)

In [26]:
y_pred

array([52.95960507, 81.65103552, 60.74243528, ..., 64.6799033 ,
       60.74243528, 41.44647036])

In [30]:
data = pd.DataFrame(data={"Predicted Orders": y_pred.flatten()})
print(data.head())

   Predicted Orders
0         52.959605
1         81.651036
2         60.742435
3         82.184943
4         64.679903


In [31]:
data

Predicted Orders
0             52.959605
1             81.651036
2             60.742435
3             82.184943
4             64.679903
...                 ...
41912        116.957280
41913         32.947177
41914         64.679903
41915         60.742435
41916         41.446470

[41917 rows x 1 columns]